/*
 * Copyright (c) 2026 Armin Reichert (MIT License)
 */

plugins {
    id "application"
    alias(libs.plugins.javafx)
    alias(libs.plugins.jlink)
    //alias(libs.plugins.osdetector)
}

dependencies {
    implementation(libs.fastutil)
    implementation(libs.bundles.tinylog)
    implementation(project(":objparser"))
    implementation(project(":meshbuilder"))
}

javafx {
    version = libs.versions.javafx.get()
    modules = ["javafx.base", "javafx.graphics", "javafx.controls"]
}

application {
    mainModule = "de.amr.meshviewer"
    mainClass  = "de.amr.meshviewer.app.Main"
}

jlink {
    options = [
        "--compress", "zip-9",
        "--strip-debug",
        "--no-header-files",
        "--no-man-pages"
    ]
    launcher {
        name = "MeshViewer FX"
    }
    jpackage {
        appVersion = "1.0"
        vendor = "Armin Reichert"
        installerOptions = []
        installerType = installerPkg
        if (osdetector.os == "windows") {
            installerOptions += ["--win-dir-chooser", "--win-menu", "--win-menu-group", "Meshviewer FX", "--win-shortcut"]
        }
    }
}
