/*
 * Copyright (c) 2026 Armin Reichert (MIT License)
 */

plugins {
    alias(libs.plugins.javafx)
    alias(libs.plugins.jlink)
    alias(libs.plugins.osdetector)
}

dependencies {
    implementation(
        project(":objparser"),
        project(":meshbuilder"),
        libs.bundles.tinylog,
        libs.gson
    )
}

application {
    mainModule = "de.amr.meshviewer"
    mainClass  = "de.amr.meshviewer.app.Main"
}

javafx {
    modules = ["javafx.base", "javafx.graphics", "javafx.controls"]
}

jlink {
    // This bullshit is only necessary because my registered domain name ends with digits. If I had known before...
    mergedModule {
        additive = false
        mergedModuleName = "de.amrsixtysix.objimporter.merged"
    }

    options = [
        "--compress", "zip-9",
        "--strip-debug",
        "--no-header-files",
        "--no-man-pages"
    ]

    launcher {
        name = "MeshViewer FX"
    }

    jpackage {
        appVersion = "0.0.1"
        vendor = "Armin Reichert"
        installerOptions = []
        installerType = installerPkg
        if (osdetector.os == "windows") {
            installerOptions += [
                "--win-dir-chooser",
                "--win-menu",
                "--win-menu-group", "Meshviewer FX",
                "--win-shortcut"
            ]
        }
    }
}

ext.isRelease = false