plugins {
    alias(libs.plugins.javafx) apply false
    alias(libs.plugins.osdetector)
    id 'maven-publish'
    id 'signing'
}

// looks up property value either from Gradle properties or from env
String prop(String name) {
    return findProperty(name) ?: System.getenv(name);
}

// Repositories and coordinates for ALL modules
allprojects {
    group = "de.amr66.objimporter"
    version = "0.0.1"

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {

    // Apply plugins
    apply plugin: "java"
    apply plugin: "maven-publish"
    apply plugin: 'signing'

    // Java toolchain
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
        }
        withSourcesJar()
        withJavadocJar()
    }

    // Compiler settings
    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(["-Xlint:deprecation", "-Xlint:unchecked"])
    }

    // Publishing artifacts to Maven central and Maven local
    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java

                pom {
                    name = 'OBJ Importer'
                    description = 'OBJ importer and JavaFX mesh view creation'
                    url = 'https://github.com/armin-reichert/javafx-objimporter'

                    licenses {
                        license {
                            name = 'MIT license'
                            url = 'https://github.com/armin-reichert/javafx-objimporter/blob/main/LICENSE'
                        }
                    }

                    developers {
                        developer {
                            id = 'armin-reichert'
                            name = 'Armin Reichert'
                            email = 'armin.reichert@web.de'
                        }
                    }

                    scm {
                        url = 'https://github.com/armin-reichert/javafx-objimporter'
                        connection = 'scm:git:https://github.com/armin-reichert/javafx-objimporter.git'
                        developerConnection = 'scm:git:https://github.com/armin-reichert/javafx-objimporter.git'
                    }
                }

            }
        }

        repositories {

            /*

            maven {
                name = "sonatype"
                url = uri("https://central.sonatype.com/api/v1/publisher/upload")
                credentials {
                    username = System.getenv("SONATYPE_USERNAME")
                    password = System.getenv("SONATYPE_PASSWORD")
                }
            }

             */

            mavenLocal()
        }
    }


    signing {
        def signingKey = System.getenv("GPG_PRIVATE_KEY")
        def signingPassword = System.getenv("GPG_PRIVATE_KEY_PASSWORD")
        if (signingKey != null && signingPassword != null) {
            useInMemoryPgpKeys(signingKey, signingPassword)
            sign publishing.publications.mavenJava
        }
    }

}


// Define installer package format depending on operating system
ext.installerPkg = [linux: "deb", "osx": "dmg", windows: "msi"][osdetector.os]

logger.lifecycle("osdetector.os         = ${osdetector.os}")
logger.lifecycle("osdetector.arch       = ${osdetector.arch}")
logger.lifecycle("osdetector.classifier = ${osdetector.classifier}")
logger.lifecycle("Installer type        = ${installerPkg}")
logger.lifecycle("Java version          = ${libs.versions.java.get()}")
logger.lifecycle("JavaFX version        = ${libs.versions.javafx.get()}")
logger.lifecycle("TinyLog version       = ${libs.versions.tinylog.get()}")
