pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        // Note: In configuration phase we cannot yet use aliases!
        id("java").apply(false)
        id("org.openjfx.javafxplugin").version("0.1.0").apply(false)
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = "javafx-objimporter"

include("objparser")
include("meshbuilder")
include("meshviewer")