name: Publish to Cloudsmith

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Publish to Cloudsmith
        env:
          CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: ./gradlew publish
