name: Publish

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --info --stacktrace
